name: Golden Stack Server Build

on:
  push:
    paths:
      - '.github/workflows/build-server.yml'
      - 'packages/server/**'
      - 'packages/babel/**'
    branches-ignore:
      - 'master'

jobs:
  build-server:
    name: Build Server
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.15'
      - name: Get yarn cache dir
        id: get-yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache yarn.lock
        id: yarn-cache
        uses: actions/cache@v1
        with:
          path: ${{ steps.get-yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install
        run: |
          yarn config set unsafe-disable-integrity-migration true -g
          yarn install --frozen-lockfile --production=false --non-interactive --cache-folder $(yarn cache dir)
      - name: Build Server
        run: |
          cp ./packages/server/.env.staging ./packages/server/.env
          yarn build:server
