name: Golden Stack Server Tests

on:
  push:
    paths:
      - '.github/workflows/test-server.yml'
      - 'packages/server/**'
      - 'packages/babel/**'
    branches-ignore:
      - 'master'

jobs:
  test-server:
    name: Test Server
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.15'
      - name: Cache MongoDB Binaries
        id: mongoms-binaries
        uses: actions/cache@v1
        with:
          path: ~/.mongodb-binaries
          key: ${{ runner.os }}-v4-2-1-mongoms-binaries
          restore-keys: |
            ${{ runner.os }}-v4-2-1-mongoms-binaries
      - name: Get yarn cache dir
        id: get-yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache yarn.lock
        id: yarn-cache
        uses: actions/cache@v1
        with:
          path: ${{ steps.get-yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install
        run: |
          yarn config set unsafe-disable-integrity-migration true -g
          yarn install --frozen-lockfile --production=false --non-interactive --cache-folder $(yarn cache dir)
      - name: Test Server
        run: |
          cp ./packages/server/.env.ci ./packages/server/.env
          yarn test:server --ci --coverage --reporters=jest-junit
        env:
          JEST_SUITE_NAME: 'Golden Stack Server Tests'
          JEST_JUNIT_OUTPUT_DIR: './reports'
          MONGOMS_SYSTEM_BINARY: '~/.mongodb-binaries'
#      - uses: codecov/codecov-action@v1.0.2
#        with:
#          token: ${{ secrets.CODECOV_TOKEN }}
